apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2020-08-25T14:21:36Z"
  generateName: prometheus-prometheus-prometheus-oper-prometheus-
  labels:
    app: prometheus
    controller-revision-hash: prometheus-prometheus-prometheus-oper-prometheus-67c99fd666
    prometheus: prometheus-prometheus-oper-prometheus
    statefulset.kubernetes.io/pod-name: prometheus-prometheus-prometheus-oper-prometheus-0
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:generateName: {}
        f:labels:
          .: {}
          f:app: {}
          f:controller-revision-hash: {}
          f:prometheus: {}
          f:statefulset.kubernetes.io/pod-name: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"26d0ef05-76d0-4437-8e36-ca80a928c817"}:
            .: {}
            f:apiVersion: {}
            f:blockOwnerDeletion: {}
            f:controller: {}
            f:kind: {}
            f:name: {}
            f:uid: {}
      f:spec:
        f:containers:
          k:{"name":"prometheus"}:
            .: {}
            f:args: {}
            f:image: {}
            f:imagePullPolicy: {}
            f:livenessProbe:
              .: {}
              f:failureThreshold: {}
              f:httpGet:
                .: {}
                f:path: {}
                f:port: {}
                f:scheme: {}
              f:periodSeconds: {}
              f:successThreshold: {}
              f:timeoutSeconds: {}
            f:name: {}
            f:ports:
              .: {}
              k:{"containerPort":9090,"protocol":"TCP"}:
                .: {}
                f:containerPort: {}
                f:name: {}
                f:protocol: {}
            f:readinessProbe:
              .: {}
              f:failureThreshold: {}
              f:httpGet:
                .: {}
                f:path: {}
                f:port: {}
                f:scheme: {}
              f:periodSeconds: {}
              f:successThreshold: {}
              f:timeoutSeconds: {}
            f:resources: {}
            f:terminationMessagePath: {}
            f:terminationMessagePolicy: {}
            f:volumeMounts:
              .: {}
              k:{"mountPath":"/etc/prometheus/certs"}:
                .: {}
                f:mountPath: {}
                f:name: {}
                f:readOnly: {}
              k:{"mountPath":"/etc/prometheus/config_out"}:
                .: {}
                f:mountPath: {}
                f:name: {}
                f:readOnly: {}
              k:{"mountPath":"/etc/prometheus/rules/prometheus-prometheus-prometheus-oper-prometheus-rulefiles-0"}:
                .: {}
                f:mountPath: {}
                f:name: {}
              k:{"mountPath":"/prometheus"}:
                .: {}
                f:mountPath: {}
                f:name: {}
          k:{"name":"prometheus-config-reloader"}:
            .: {}
            f:args: {}
            f:command: {}
            f:env:
              .: {}
              k:{"name":"POD_NAME"}:
                .: {}
                f:name: {}
                f:valueFrom:
                  .: {}
                  f:fieldRef:
                    .: {}
                    f:apiVersion: {}
                    f:fieldPath: {}
            f:image: {}
            f:imagePullPolicy: {}
            f:name: {}
            f:resources:
              .: {}
              f:limits:
                .: {}
                f:cpu: {}
                f:memory: {}
              f:requests:
                .: {}
                f:cpu: {}
                f:memory: {}
            f:terminationMessagePath: {}
            f:terminationMessagePolicy: {}
            f:volumeMounts:
              .: {}
              k:{"mountPath":"/etc/prometheus/config"}:
                .: {}
                f:mountPath: {}
                f:name: {}
              k:{"mountPath":"/etc/prometheus/config_out"}:
                .: {}
                f:mountPath: {}
                f:name: {}
          k:{"name":"rules-configmap-reloader"}:
            .: {}
            f:args: {}
            f:image: {}
            f:imagePullPolicy: {}
            f:name: {}
            f:resources:
              .: {}
              f:limits:
                .: {}
                f:cpu: {}
                f:memory: {}
              f:requests:
                .: {}
                f:cpu: {}
                f:memory: {}
            f:terminationMessagePath: {}
            f:terminationMessagePolicy: {}
            f:volumeMounts:
              .: {}
              k:{"mountPath":"/etc/prometheus/rules/prometheus-prometheus-prometheus-oper-prometheus-rulefiles-0"}:
                .: {}
                f:mountPath: {}
                f:name: {}
        f:dnsPolicy: {}
        f:enableServiceLinks: {}
        f:hostname: {}
        f:restartPolicy: {}
        f:schedulerName: {}
        f:securityContext:
          .: {}
          f:fsGroup: {}
          f:runAsGroup: {}
          f:runAsNonRoot: {}
          f:runAsUser: {}
        f:serviceAccount: {}
        f:serviceAccountName: {}
        f:subdomain: {}
        f:terminationGracePeriodSeconds: {}
        f:volumes:
          .: {}
          k:{"name":"config"}:
            .: {}
            f:name: {}
            f:secret:
              .: {}
              f:defaultMode: {}
              f:secretName: {}
          k:{"name":"config-out"}:
            .: {}
            f:emptyDir: {}
            f:name: {}
          k:{"name":"prometheus-prometheus-prometheus-oper-prometheus-db"}:
            .: {}
            f:emptyDir: {}
            f:name: {}
          k:{"name":"prometheus-prometheus-prometheus-oper-prometheus-rulefiles-0"}:
            .: {}
            f:configMap:
              .: {}
              f:defaultMode: {}
              f:name: {}
            f:name: {}
          k:{"name":"tls-assets"}:
            .: {}
            f:name: {}
            f:secret:
              .: {}
              f:defaultMode: {}
              f:secretName: {}
    manager: kube-controller-manager
    operation: Update
    time: "2020-08-25T14:21:36Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:conditions:
          k:{"type":"ContainersReady"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
          k:{"type":"Initialized"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
          k:{"type":"Ready"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
        f:containerStatuses: {}
        f:hostIP: {}
        f:phase: {}
        f:podIP: {}
        f:podIPs:
          .: {}
          k:{"ip":"172.18.0.10"}:
            .: {}
            f:ip: {}
        f:startTime: {}
    manager: kubelet
    operation: Update
    time: "2020-08-25T14:23:07Z"
  name: prometheus-prometheus-prometheus-oper-prometheus-0
  namespace: istio-system
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: StatefulSet
    name: prometheus-prometheus-prometheus-oper-prometheus
    uid: 26d0ef05-76d0-4437-8e36-ca80a928c817
  resourceVersion: "1228"
  selfLink: /api/v1/namespaces/istio-system/pods/prometheus-prometheus-prometheus-oper-prometheus-0
  uid: 8dbd28b8-714a-4765-9ee1-6a38c3e27d94
spec:
  containers:
  - args:
    - --web.console.templates=/etc/prometheus/consoles
    - --web.console.libraries=/etc/prometheus/console_libraries
    - --config.file=/etc/prometheus/config_out/prometheus.env.yaml
    - --storage.tsdb.path=/prometheus
    - --storage.tsdb.retention.time=10d
    - --web.enable-lifecycle
    - --storage.tsdb.no-lockfile
    - --web.external-url=http://prometheus-prometheus-oper-prometheus.istio-system:9090
    - --web.route-prefix=/
    image: quay.io/prometheus/prometheus:v2.18.2
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 6
      httpGet:
        path: /-/healthy
        port: web
        scheme: HTTP
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 3
    name: prometheus
    ports:
    - containerPort: 9090
      name: web
      protocol: TCP
    readinessProbe:
      failureThreshold: 120
      httpGet:
        path: /-/ready
        port: web
        scheme: HTTP
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 3
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: FallbackToLogsOnError
    volumeMounts:
    - mountPath: /etc/prometheus/config_out
      name: config-out
      readOnly: true
    - mountPath: /etc/prometheus/certs
      name: tls-assets
      readOnly: true
    - mountPath: /prometheus
      name: prometheus-prometheus-prometheus-oper-prometheus-db
    - mountPath: /etc/prometheus/rules/prometheus-prometheus-prometheus-oper-prometheus-rulefiles-0
      name: prometheus-prometheus-prometheus-oper-prometheus-rulefiles-0
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: prometheus-prometheus-oper-prometheus-token-9rksz
      readOnly: true
  - args:
    - --log-format=logfmt
    - --reload-url=http://127.0.0.1:9090/-/reload
    - --config-file=/etc/prometheus/config/prometheus.yaml.gz
    - --config-envsubst-file=/etc/prometheus/config_out/prometheus.env.yaml
    command:
    - /bin/prometheus-config-reloader
    env:
    - name: POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    image: quay.io/coreos/prometheus-config-reloader:v0.38.1
    imagePullPolicy: IfNotPresent
    name: prometheus-config-reloader
    resources:
      limits:
        cpu: 100m
        memory: 25Mi
      requests:
        cpu: 100m
        memory: 25Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: FallbackToLogsOnError
    volumeMounts:
    - mountPath: /etc/prometheus/config
      name: config
    - mountPath: /etc/prometheus/config_out
      name: config-out
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: prometheus-prometheus-oper-prometheus-token-9rksz
      readOnly: true
  - args:
    - --webhook-url=http://127.0.0.1:9090/-/reload
    - --volume-dir=/etc/prometheus/rules/prometheus-prometheus-prometheus-oper-prometheus-rulefiles-0
    image: docker.io/jimmidyson/configmap-reload:v0.3.0
    imagePullPolicy: IfNotPresent
    name: rules-configmap-reloader
    resources:
      limits:
        cpu: 100m
        memory: 25Mi
      requests:
        cpu: 100m
        memory: 25Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: FallbackToLogsOnError
    volumeMounts:
    - mountPath: /etc/prometheus/rules/prometheus-prometheus-prometheus-oper-prometheus-rulefiles-0
      name: prometheus-prometheus-prometheus-oper-prometheus-rulefiles-0
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: prometheus-prometheus-oper-prometheus-token-9rksz
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostname: prometheus-prometheus-prometheus-oper-prometheus-0
  nodeName: minikube
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 2000
    runAsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccount: prometheus-prometheus-oper-prometheus
  serviceAccountName: prometheus-prometheus-oper-prometheus
  subdomain: prometheus-operated
  terminationGracePeriodSeconds: 600
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: config
    secret:
      defaultMode: 420
      secretName: prometheus-prometheus-prometheus-oper-prometheus
  - name: tls-assets
    secret:
      defaultMode: 420
      secretName: prometheus-prometheus-prometheus-oper-prometheus-tls-assets
  - emptyDir: {}
    name: config-out
  - configMap:
      defaultMode: 420
      name: prometheus-prometheus-prometheus-oper-prometheus-rulefiles-0
    name: prometheus-prometheus-prometheus-oper-prometheus-rulefiles-0
  - emptyDir: {}
    name: prometheus-prometheus-prometheus-oper-prometheus-db
  - name: prometheus-prometheus-oper-prometheus-token-9rksz
    secret:
      defaultMode: 420
      secretName: prometheus-prometheus-oper-prometheus-token-9rksz
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-08-25T14:21:36Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020-08-25T14:23:07Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2020-08-25T14:23:07Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-08-25T14:21:36Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://8f4baf135e560ba0b9d2508eebb9451be6101f53ba557ab33e23f3ad55ce1f00
    image: quay.io/prometheus/prometheus:v2.18.2
    imageID: docker-pullable://quay.io/prometheus/prometheus@sha256:4d3303d1eb424e345cf48969bb7575d4d58472ad783ac41ea07fba92686f7ef5
    lastState:
      terminated:
        containerID: docker://6c841ec00f1645f57817fc4da5561689919694e72700a2f2c379fac9664803b6
        exitCode: 1
        finishedAt: "2020-08-25T14:22:30Z"
        message: |
          22:30.844Z caller=main.go:678 msg="Starting TSDB ..."
          level=info ts=2020-08-25T14:22:30.849Z caller=head.go:575 component=tsdb msg="Replaying WAL, this may take awhile"
          level=info ts=2020-08-25T14:22:30.849Z caller=head.go:624 component=tsdb msg="WAL segment loaded" segment=0 maxSegment=0
          level=info ts=2020-08-25T14:22:30.849Z caller=head.go:627 component=tsdb msg="WAL replay completed" duration=325.942Âµs
          level=info ts=2020-08-25T14:22:30.850Z caller=main.go:694 fs_type=EXT4_SUPER_MAGIC
          level=info ts=2020-08-25T14:22:30.851Z caller=main.go:695 msg="TSDB started"
          level=info ts=2020-08-25T14:22:30.851Z caller=main.go:799 msg="Loading configuration file" filename=/etc/prometheus/config_out/prometheus.env.yaml
          level=info ts=2020-08-25T14:22:30.851Z caller=main.go:547 msg="Stopping scrape discovery manager..."
          level=info ts=2020-08-25T14:22:30.851Z caller=main.go:561 msg="Stopping notify discovery manager..."
          level=info ts=2020-08-25T14:22:30.851Z caller=main.go:583 msg="Stopping scrape manager..."
          level=info ts=2020-08-25T14:22:30.851Z caller=main.go:557 msg="Notify discovery manager stopped"
          level=info ts=2020-08-25T14:22:30.851Z caller=manager.go:882 component="rule manager" msg="Stopping rule manager..."
          level=info ts=2020-08-25T14:22:30.851Z caller=manager.go:892 component="rule manager" msg="Rule manager stopped"
          level=info ts=2020-08-25T14:22:30.851Z caller=main.go:543 msg="Scrape discovery manager stopped"
          level=info ts=2020-08-25T14:22:30.851Z caller=main.go:577 msg="Scrape manager stopped"
          level=info ts=2020-08-25T14:22:30.854Z caller=notifier.go:601 component=notifier msg="Stopping notification manager..."
          level=info ts=2020-08-25T14:22:30.854Z caller=main.go:749 msg="Notifier manager stopped"
          level=error ts=2020-08-25T14:22:30.854Z caller=main.go:758 err="error loading config from \"/etc/prometheus/config_out/prometheus.env.yaml\": couldn't load configuration (--config.file=\"/etc/prometheus/config_out/prometheus.env.yaml\"): open /etc/prometheus/config_out/prometheus.env.yaml: no such file or directory"
        reason: Error
        startedAt: "2020-08-25T14:22:30Z"
    name: prometheus
    ready: true
    restartCount: 1
    started: true
    state:
      running:
        startedAt: "2020-08-25T14:23:02Z"
  - containerID: docker://fa491064201c529cd1c2f0a600686fdd7bbcb6ba16bc347d2c9c276e6a7fe285
    image: quay.io/coreos/prometheus-config-reloader:v0.38.1
    imageID: docker-pullable://quay.io/coreos/prometheus-config-reloader@sha256:d1cce64093d4a850d28726ec3e48403124808f76567b5bd7b26e4416300996a7
    lastState: {}
    name: prometheus-config-reloader
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2020-08-25T14:23:01Z"
  - containerID: docker://e55f02fefe9a96b3482afc0f88d8bbb116cb5e5c05418ce5430df760b150bbf2
    image: jimmidyson/configmap-reload:v0.3.0
    imageID: docker-pullable://jimmidyson/configmap-reload@sha256:d107c7a235c266273b1c3502a391fec374430e5625539403d0de797fa9c556a2
    lastState: {}
    name: rules-configmap-reloader
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2020-08-25T14:23:01Z"
  hostIP: 172.17.0.3
  phase: Running
  podIP: 172.18.0.10
  podIPs:
  - ip: 172.18.0.10
  qosClass: Burstable
  startTime: "2020-08-25T14:21:36Z"
